// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// order4
long order4(long n);
RcppExport SEXP _gghilbertstrings_order4(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(order4(n));
    return rcpp_result_gen;
END_RCPP
}
// d2xy
NumericVector d2xy(long n, long d);
RcppExport SEXP _gghilbertstrings_d2xy(SEXP nSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long >::type n(nSEXP);
    Rcpp::traits::input_parameter< long >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(d2xy(n, d));
    return rcpp_result_gen;
END_RCPP
}
// d2xy2
NumericMatrix d2xy2(long n, NumericVector d);
RcppExport SEXP _gghilbertstrings_d2xy2(SEXP nSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(d2xy2(n, d));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gghilbertstrings_order4", (DL_FUNC) &_gghilbertstrings_order4, 1},
    {"_gghilbertstrings_d2xy", (DL_FUNC) &_gghilbertstrings_d2xy, 2},
    {"_gghilbertstrings_d2xy2", (DL_FUNC) &_gghilbertstrings_d2xy2, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_gghilbertstrings(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
