# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Finds the order of the next highest number to the power of 4
#' @param n number
#' @return Order of next highest number 4^x
order4 <- function(n) {
    .Call(`_gghilbertstrings_order4`, n)
}

#' Returns the x/y-position for a distance d in n possible values
#'
#' @param n First value
#' @param d Second value
#' @return Vector of x y
d2xy <- function(n, d) {
    .Call(`_gghilbertstrings_d2xy`, n, d)
}

#' Returns the x/y-position for a Vector of distances d in n possible values
#'
#' @param n Size of
#' @param d Second value
#' @return Matrix of x y values
d2xy2 <- function(n, d) {
    .Call(`_gghilbertstrings_d2xy2`, n, d)
}

