# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns the position for a distance in n
#'
#' @param n First value
#' @param d Second value
#' @return Vector of x y
d2xy <- function(n, d) {
    .Call(`_gghilbertstrings_d2xy`, n, d)
}

